config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :slots

  resources :advisors
  devise_for :users
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advisor.rb
class Advisor < ApplicationRecord
	has_many :slots 

	accepts_nested_attributes_for :slots

	# has_many :bookings

	# def advisor_timeslots
	# time_iteration
	# end

	# def time_iteration
	# 	advisor_one = Advisor.find(1)
	#   	start_time = advisor_one.start_time
	#   	end_time = advisor_one.end_time
	# 	times = [start_time.strftime('%H:%M')]
	# 	begin
	# 	start_time += 30.minutes
	# 	times << start_time.strftime('%H:%M')
	# 	end while start_time < end_time
	# 	return times
	# end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :slots, optional: true

end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :advisor, optional: true
  has_one :booking
  # belongs_to :booking, optional: true
  
  enum status: [:free, :booked]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :bookings


end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  before_action :set_advisor, only: [:show, :edit, :update, :destroy]

  # GET /advisors
  # GET /advisors.json
  def index
    @advisors = Advisor.all
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
    @advisor = Advisor.find(params[:id])
  end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
  end

  # GET /advisors/1/edit
  def edit
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(advisor_params)

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: 'Advisor was successfully created.' }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1
  # PATCH/PUT /advisors/1.json
  def update
    respond_to do |format|
      if @advisor.update(advisor_params)
        format.html { redirect_to @advisor, notice: 'Advisor was successfully updated.' }
        format.json { render :show, status: :ok, location: @advisor }
      else
        format.html { render :edit }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy
    @advisor.destroy
    respond_to do |format|
      format.html { redirect_to advisors_url, notice: 'Advisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor
      @advisor = Advisor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advisor_params
      params.require(:advisor).permit(:name, :start_time, :end_time)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
    @slots = Slot.free

  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  @booking = Booking.find(params[:id])

  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :slot_id, :name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.free
    @advisors = Advisor.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
    @advisors = Advisor.all
  end

  # GET /slots/new
  def new
    @slot = Slot.new
    @advisors = Advisor.all
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
      @slot = Slot.find(params[:id])

    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:start_time, :end_time, :advisor_id, :user_id, :name, advisors_attributes:[:name])
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/advisors/_form.html.erb
<%= form_with(model: advisor, local: true) do |form| %>
  <% if advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% advisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :advisor_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

  <!-- 

  <div class="field">
    <%#= form.label :start_time %>
    <%#= form.datetime_select :start_time, :minute_step => 30, id: :advisor_start_time %>
  </div>


  <div class="field">
    <%#= form.label :end_time %>
    <%#= form.datetime_select :end_time, :minute_step => 30, id: :advisor_end_time %>
  </div>

 -->

app/views/advisors/edit.html.erb
<h1>Editing Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Advisors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
<!--       <th>Start time</th>
      <th>End time</th>
 -->      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisors.each do |advisor| %>
      <tr>
        <td><%= advisor.name %></td>
        <td><%#= advisor.start_time %></td>
        <td><%#= advisor.end_time %></td>
        <td><%#= link_to 'Show', advisor %></td>
        <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
        <td><%= link_to 'Destroy', advisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advisor', new_advisor_path %>

app/views/advisors/new.html.erb
<h1>New Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Back', advisors_path %>

app/views/advisors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @advisor.name %>
</p>


<%= link_to 'Edit', edit_advisor_path(@advisor) %> |
<%= link_to 'Back', advisors_path %>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>  
<% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :slot_id %>
    <%= form.collection_select :slot, Slot.free, :id, :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>





<!--   <div class="field">
    <%#= form.label :name %>
    <%#= form.collection_select :name, Slot.free, :name, :name %>
  </div>



  <div class="field">
    <%#= form.label :slot_id %>
    <%#= form.collection_select :slot_id, Slot.free, :id, :name %>
  </div> -->



  <!-- 
  <div class="field">
    <%#= form.label :user_id, "Booked by" %>
    <%#= form.collection_select :user_id, User.all, :id, :email %>
  </div>

 
  <div class="field">
    <%#= form.label :slot_id, "slot_id" %>
    <%#= form.collection_select :slot_id, Slot.free, :id, :id %>
  </div> -->

   <!-- 
  <div class="field">
    <%# if params[:slot_id].present? %>
    <%#= form.hidden_field :slot_id, Slot.free, value: params[:slot_id] %>
    <%# end %>
  </div> -->

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.email %></td>
        <td><%= booking.slot_id %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Booking', new_booking_path %>

<% puts @booking.inspect %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>


<%= render 'form', booking: @booking %>


<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @booking.user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @booking.slot_id%>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>


<% puts @booking.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timeslot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Cal</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><a href="/bookings/new">Student Booking</a></li>
        <li><a href="/advisors">List of Advisors</a></li>
        <li><a href="/slots">Time slots</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= current_user.email%></a></li>
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <% else %>
     <li><%= link_to 'Login', new_user_session_path  %></li>
     <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/slots/_form.html.erb
<%= form_with(model: slot, local: true) do |form| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :slot_start_time, :minute_step => 30 %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :slot_end_time, :minute_step => 30 %>
  </div>

  <div class="field">
    <%= form.label :advisor_id %>
    <%= form.collection_select :advisor_id, Advisor.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>






<%#= collection_select(:name, :advisor_id, Advisor.all, :name, :name, prompt: true) %>

<%#= form.fields_for :advisor do |ff| %>
<!--       <div>
        <%#= ff.hidden_field :name %>
      </div> -->
  <%# end %>

<!-- <div class="field">
    <%#= form.label :advisor_id %>
    <%#= form.collection_select :advisor_id, Advisor.all, :id, :id %>
  </div>

  <div class="field">
    <%#= form.label :name %>
    <%#= form.collection_select :name, Advisor.all, :name, :name %>
  </div>  -->


<!--  <div class="field">
    <%#= form.label :start_time %>
    <%#= form.collection_select :advisor_id, Advisor.all, :id, :start_time %>
  </div>

  <div class="field">
    <%#= form.label :name %>
    <%#= form.select :advisor_name, Advisor.all.collect { |p| p.name }, include_blank: true %>
  </div>  -->

  <!--  <div class="field">
    <%#= form.label :advisor_id %>
    <%#= form.collection_select :advisor_id, Advisor.all, :id, :name%>
  </div>
 -->

<!--   <div class="field">
    <%#= hidden_field_tag :name, @advisor_name %>
  </div>


  <div class="field">
    <%#= form.label :name %>
    <%#= collection_select(:name, :advisor_id, Advisor.all, :name, :name, prompt: true) %>
    <%#= select("slot", "advisor_id", Advisor.all.collect {|a| [ a.name, a.id ] }, {prompt: 'Select Advisor'}) %>
  </div> -->

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slots</h1>

<table class = "table-bordered">
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Advisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.start_time %></td>
        <td><%= slot.end_time %></td>
        <td><%= slot.advisor.name%></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @slot.end_time%>
</p>

<p>
  <strong>Advisor:</strong>
  <%= @slot.advisor.name %>
</p>

<% puts @slot.inspect %>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>